### ISSUE TITLE
Apple Watch Support

### ISSUE THREAD

**Issue by themanontv** [7enChan/stillapp#42]
**Feature Description**
Apple Watch support for listening while doing workouts when you have no phone.

I would like to...
Be able to listen to an audiobook while I'm going for a run without my phone much like how the Apple Books app works

This would help because...
For many runners we don't often bring our phones with us and so being able to get audiobooks on the go would be ideal. Personally I don't like the implementation in something like plappa too much because the watch app essentially acts like another client and the downloads are a bit too large. 

Overcast has a decent implementation for podcasts where it compresses the audio for the watch to save on space. This might be a tricky thing to implement but would be a killer feature.

In a perfect world we could stream from the watch but that's not going to happen :(

**Comment by 7enChan** [comment]
Thanks!
I plan to support Apple Watch in the future, though it's not a high priority right now. I intend to keep the watch app simple and lightweight, focusing on a solid playback experience rather than complex features.

**Comment by themanontv** [comment]
That's fair enough, I see it as a nice potential for the future but yeah, there are more pressing issues! Thanks for the app!

**Comment by adastorm** [comment]
I would also love this feature! But I totally get that it would take time!

**Comment by 7enChan** [comment]
I'd love to build this. The only catch is that I don't own an Apple Watch and honestly don't have a personal use case for one, so the simulator is all I have.

To be honest, without a real device and daily usage, it's very hard for me to guarantee a great user experience. With the phone app, I use it every day, which allows me to constantly polish the little details. I worry that building a standalone watch app without heavy personal use might result in an experience that falls short of expectations.

That said, if anyone in this thread is up for being a beta tester on their real watch, let me know! It will help me prioritize this for a future update.

**Comment by adastorm** [comment]
I would love to be a beta tester if you've made an Apple Watch app. Sometimes I love to listen to podcasts when I go on a run and I would love to listen to audiobooks as well.

**Comment by themanontv** [comment]
My own two cents on the issue from my experience using Audiobookshelf apps: I've used an app called prologue that does Apple Watch support really well for Audiobookshelf. The key combination seems to be that it stores progress in iCloud as a fallback for syncing and so that's probably a good starting point, when I used Plappa for this purpose it was a bit unstable and progress was hard to keep in line as it relied on the watch and phone syncing with my server which wasn't always consistent.

I think if you rely too heavily on using the Audiobookshelf server its own when it's only local it can be really flaky.

**Comment by themanontv** [comment]
I'd also be happy to test this as well btw!

**Comment by 7enChan** [comment]
Thanks for volunteering! I'm starting to look into this now. It will take a little time for me to get familiar with watchOS first, but I'll keep you updated.

**Comment by 7enChan** [comment]
Update: the first version of the Apple Watch app is now live on [TestFlight](https://testflight.apple.com/join/JgVXybzQ)!

@themanontv @adastorm Please update to the latest build and give it a try.Since this is the first iteration, expect a few rough edges. Let me know how it works for your daily routines, and feel free to share any feedback if you run into problems.

**Comment by so7ow** [comment]
I just installed the TestFlight version. At first, I wasn't able to launch the watch app. I tapped it and it seemed to register the tap, but it just ... didn't launch. No error, no nothing. A reboot of the watch has fixed it. 👍🏻

For what it's worth, the biggest thing I'd need to be able to use this regularly is a download to watch function. 

Playback working just fine so far, picked up an in-progress book without issue. 

Apple Watch Ultra 2
watchOS 26.5

**Comment by 7enChan** [comment]
Thanks for testing it!

The launch issue sounds like a watchOS / TestFlight installation hiccup, especially since a reboot fixed it, but I’ll keep an eye on it.

Download to Watch is actually included in this build. You can swipe left on a book and tap Download, then find downloaded items in the Downloaded section.

**Comment by so7ow** [comment]
> You can swipe left on a book and tap Download

Ah! Great, I'll give it a try.

**Comment by so7ow** [comment]
> Thanks for testing it!

I've tried several different iPhone/Watch apps for AudioBookshelf and I've had the same problem with each of them, including Still, now: when I go back and forth between the iPhone and the Watch app, my listen progress doesn't sync consistently and I find myself constantly seeking around and trying to remember where I was. Listen history logs on some apps make this a little better on the phone, but I've yet to find a seamless way to move between devices. Any thoughts on making that work better, or anything I could provide to help track it down?

**Comment by 7enChan** [comment]
Could you provide some specific reproduction steps? For example, after listening offline on the Watch, did it reconnect to the phone before you switched? The Watch's progress sync relies on its connection to the phone.

**Comment by so7ow** [comment]
Well here's what I do:

1. Go out for a walk/run and listen to a book on Watch/bluetooth without phone nearby.

2. Return home, bringing Watch and phone back into proximity with each other. Is this what you mean by reconnecting? Do I need to do something special to reconnect in this case?

3. Later, with watch and phone still near each other, play the same book on phone, and find it's not aware of the session from earlier on the Watch.

**Comment by 7enChan** [comment]
> 2. Return home, bringing Watch and phone back into proximity with each other. Is this what you mean by reconnecting? Do I need to do something special to reconnect in this case?

You shouldn't need to do anything special. Basically, as long as the Watch app has network access to the abs server (either directly or through your iPhone), it should be fine.？

> 3. Later, with watch and phone still near each other, play the same book on phone, and find it's not aware of the session from earlier on the Watch.

It can take a moment for the Watch to come back online or reconnect to the phone. When you open the iPhone app, try giving it a few seconds to see if the progress catches up.

Ideally, you shouldn't have to open the Watch app at all. If it really gets stuck, opening the Watch app can force a sync as a last resort, but I'm trying to avoid relying on clunky workarounds like that.

I just pushed a new build that improves the sync logic. Please give it another try!

**Comment by so7ow** [comment]
> Please give it another try!

Will do. I forgot to mention: my watch is a cellular model, with an active plan, so network connectivity is (almost) always available, if that makes any difference.

**Comment by so7ow** [comment]
> a new build that improves the sync logic.

Ok, here's what happened today on the new version:

1. Listen to a book in the car on iPhone/bluetooth (not carplay, if it matters). Watch is also present for whole duration, but not used for playback.
2. Get home, go inside. Start listening on Watch/bluetooth. Phone is still present but not used. Watch app is not aware of the playback session from the car, starts playback where I was this morning before driving.

**Comment by 7enChan** [comment]
> my watch is a cellular model, with an active plan, so network connectivity is (almost) always available, if that makes any difference.

If your Watch can connect to the ABS server via cellular, it should definitely make the progress sync much more reliable.

> Watch app is not aware of the playback session from the car, starts playback where I was this morning before driving.

This happens because the part where the Watch fetches the latest progress wasn’t robust enough. I’ve strengthened this logic in the latest build, so please update and try it again!

One more thing to check: please make sure Background App Refresh is turned on for your Watch, and that Still is enabled in that list (it's on by default unless you manually turned it off, so usually no adjustment is needed).

**Comment by so7ow** [comment]
> One more thing to check: please make sure Background App Refresh is turned on for your Watch, and that Still is enabled in that list (it's on by default unless you manually turned it off, so usually no adjustment is needed).

Confirmed this was already enabled. I'll try out the new version this weekend.

**Comment by so7ow** [comment]
Same behavior for me still. Sessions on phone are not reliably picked up on the watch.

I listened in the car on the phone. When I got home I pressed play on the watch and it picked up from a couple chapters back.

**Comment by 7enChan** [comment]
Thanks, I want to clarify one detail: when you said “I pressed play on the Watch”, did you open the Still Watch app and start the book from Continue, or did you press play from the system Now Playing screen without opening Still?

Also, when you open Still on the Watch, can it connect to your Audiobookshelf server and stream the book normally?

**Comment by so7ow** [comment]
> did you open the Still Watch app and start the book from Continue

Yeah, I always launch the app (on the phone or watch) and wait a moment to give it a chance to sync before hitting the book in Continue. Then when done listening, I press pause before switching away from the app. Open to any other steps you think might allow things to work better. 

> can it connect to your Audiobookshelf server and stream the book normally?

Yep, streaming/playback work fine, just often not from the right spot!

**Comment by 7enChan** [comment]
This issue is turning out to be more complex than I expected. I've just pushed another optimized version—please update to the latest build(249) and give it a try!

> Open to any other steps you think might allow things to work better.

No need for any extra steps right now; just keep using it the way you normally do.

**Comment by sohansubhash** [comment]
Hi! I'm so glad I found this thread. I'm also a runner and I've been looking for a reliable Audiobookshelf app for watchOS.

I've was using Prologue on iOS/watchOS but that client only supports AudioBooks. I needed podcast support.

I'm joined the Still TestFlight. Here is my initial feedback.

Simple feature requests:
1. There is no complication yet. A simple glyph of the still logo will work.
2. Missing sleep timer. This is a common feature on most podcast/book clients.

I think it's worth examining the Audible watch app. They've nailed all the main features for watchOS.

More complicated feature request:

- Ability to browse podcasts library. Manually download episodes or add them to the queue.

I understand that Still's interface is intended to be minimal (and I appreciate that on iOS). But the watchOS client is too dependent on the phone to function. Currently you have to queue podcast episodes from the phone to get them to appear on the watch.

I think adding a few more features will balance the minimalism and functionality. Thank you for developing this app.

**Comment by sohansubhash** [comment]
Went for a run to test out the watchOS app. some additional feedback:

1. Podcasts do not continuous play from the queue. After an episode ends I have to open the app to select the next one.
2. There is no way to reorder the episodes in the queue
3. There is no way to mark an episode as played. or remove it from the queue.

If the queue is going to be the primary vehicle for getting episodes onto the watch, it would be great to have these friction points fixed. Thank you!

**Comment by 7enChan** [comment]
Thanks for taking the time to test and provide feedback. I have released a new version, build 262, which you can update to and try out.

> There is no complication yet. A simple glyph of the still logo will work.

Build 262 now supports lock screen widgets and watch faces.

> Missing sleep timer. This is a common feature on most podcast/book clients.

I haven't thought of a use case for this, as my understanding is that using the watch mostly requires Bluetooth headphones, and stopping playback can simply be controlled via the headphones. Apple Books and Podcasts don't have this either, so I won't consider supporting it for now.

> Ability to browse podcasts library. Manually download episodes or add them to the queue.

I feel that browsing the library is a bit too heavy, and I want to keep the app lightweight. I might consider adding a "Latest" list in the future if the implementation cost is low. Manual downloading is already supported.

> 1. Podcasts do not continuous play from the queue. After an episode ends I have to open the app to select the next one.

This should be a bug. It has been fixed in build 262, you can test it out.

> 2. There is no way to reorder the episodes in the queue

Reordering is too complex for Watch interactions, so I won't consider implementing it. However, the Watch queue currently works differently from the iPhone. When you switch to episode A in the queue to start playing, and then switch to another episode B, episode A will return to the queue. This effectively serves as a workaround for reordering.

> 3. There is no way to mark an episode as played. or remove it from the queue.

Build 262 now supports marking an episode as played.

**Comment by sohansubhash** [comment]
Thanks for the quick update. I'm now on the latest build 262.

I was able to verify that the following works:
- continuous play of the queue
- playing an episode out of order of the queue returns back to the previous queue position after it's done. it's an good enough substitute for reordering.
- new watchOS complication

I agree that the simplicity of the queue system works but there are still some friction points:

1. Episodes in the queue don't auto-download on the watch. Having to manually download each item is really inconvenient. This is a feature available on all other watch podcast apps like: Apple, Overcast, and Pocket Casts. Maybe you might need to add a setting toggle in the iOS app to so that users can opt in to this.
2. No cleanup of downloads after an episode is completed. The downloaded episode remains on the watch until the user manually removes it. Auto clean up would streamline the process of managing episodes on the watch. This is another good candidate for a settings toggle in the iOS app.

Regarding the Sleep timer.

Modern Apple Watch models can play audio out of the onboard speaker, no bluetooth headphones are required. A use case I have is playing audio before bed. A sleep timer stops the audio from playing after I've fallen asleep.

I noticed that there is already a shortcut action called `Start sleep timer` but I could get it's functionality to work on the watch. The shortcut does not surface an error, and fails to stop the audio from playing.

Instead of adding a sleep timer UI affordance to the watchOS application, I would greatly appreciate if you could debug the shortcut. That solves the problem.

Thanks!

**Comment by 7enChan** [comment]
Thanks again for testing this!

Regarding auto-download and auto-cleanup, these are definitely on the roadmap, but for now, the priority is making sure the core functionality works smoothly.

About the Sleep Timer—to be honest, I really didn't know much about the Apple Watch lineup. I actually had to buy a secondhand S7 just recently as a test device for development, so the current Watch app design primarily uses Apple's native apps as a reference for best practices. But if the latest Watches can play audio through the speaker and the battery lasts long enough, leaving it in the bedroom away from the phone is a totally valid use case. I'll look into adding a simpler sleep timer than the iPhone version in the next build.

**Comment by so7ow** [comment]
> Yep, streaming/playback work fine, just often not from the right spot!

My issues seem to be resolved. Not sure which build did it but it's been days since I've had a missed sync. 👍🏻

**Comment by 7enChan** [comment]
> My issues seem to be resolved. Not sure which build did it but it's been days since I've had a missed sync. 👍🏻

The recent builds have indeed included almost all possible enhancements and optimizations for progress syncing. However, due to the Apple Watch having much stricter background management mechanisms than the iPhone, there may still be some edge cases where progress doesn't sync immediately.

Additionally, the Watch's login authentication access token currently relies on the iPhone, and Audiobookshelf's default expiration time is 1 hour (3600s). Because of this, if the Watch is disconnected from the iPhone for up to an hour, it might lose its streaming capability, which also affects the success rate of progress syncing. Increasing the default ACCESS_TOKEN_EXPIRY duration in abs can help improve reliability.
